# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ryan J. Salva
email: me@ryanjsalva.com
description: "JavaScript Developer, Apache Cordova Committer, Visual Studio Program Manager, Public Speaker, CrossFitter, SciFi Connoisseur and Whiskey Enthusiast."
baseurl: "" # the subpath of your site, e.g. /blog
timezone: MX
url: "http://ryanjsalva.com" 
twitter_username: ryanjsalva
github_username:  ryanjsalva
linkedin_username: ryanjsalva
paginate: 5

# Build settings
markdown: kramdown

# Plugins
gems: [jekyll-paginate]
